# Generated by Django 4.2 on 2024-07-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_lesson_course'),
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
