# Generated by Django 4.2 on 2024-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_country_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link_to_payment',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии'),
        ),
    ]
