# Generated by Django 4.2 on 2024-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payment_link_to_payment_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'наличные'), ('remittance', 'перевод на счет')], max_length=150, null=True, verbose_name='способ оплаты'),
        ),
    ]
