# Generated by Django 4.2 on 2024-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription',
            field=models.BooleanField(blank=True, null=True, verbose_name='подписка'),
        ),
    ]
